[package]
name = "LPCoin"
version = "0.3.0"

[dependencies]
AptosFramework = { git = "https://github.com/aptos-labs/aptos-core.git", subdir = "aptos-move/framework/aptos-framework/", rev = "83641d3f083762f31700060e5e95fbb1cbc28bf0" }

[addresses]
ResourceAccountDeployer = "0x21a19ab56c7521fcc4af7eef657d1c2b61a96b0e23c0f94426626ed3d830fe5c"

